# Generated by Django 5.1 on 2024-08-26 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goshenlechem_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='contact',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='diary',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goshenlechem_register.position'),
        ),
    ]
